#ifndef Wires_h
#define Wires_h

#define RIGHT_MOTOR_ENABLE 6
#define LEFT_MOTOR_ENABLE 7
#define LEFT_MOTOR_TOP_WIRE 8
#define LEFT_MOTOR_BOTTOM_WIRE 9
#define RIGHT_MOTOR_TOP_WIRE 10
#define RIGHT_MOTOR_BOTTOM_WIRE 11

#define RIGHT_LINE_SENSOR 2
#define LEFT_LINE_SENSOR 3

#define LEFT_MOTOR_BCD_1 50
#define LEFT_MOTOR_BCD_2 51
#define RIGHT_MOTOR_BCD_1 52
#define RIGHT_MOTOR_BCD_2 53

#define FRONT_LEFT_DISTANCE 0
#define FRONT_RIGHT_DISTANCE 1
#define BACK_LEFT_DISTANCE 2
#define BACK_RIGHT_DISTANCE 3

#endif
