#ifndef Wires_h
#define Wires_h

#define RIGHT_MOTOR_ENABLE 6
#define LEFT_MOTOR_ENABLE 7
#define LEFT_MOTOR_TOP_WIRE 8
#define LEFT_MOTOR_BOTTOM_WIRE 9
#define RIGHT_MOTOR_TOP_WIRE 10
#define RIGHT_MOTOR_BOTTOM_WIRE 11

#define RIGHT_LINE_SENSOR 12
#define LEFT_LINE_SENSOR 13

#define RIGHT_MOTOR_BCD_WHITE_B 50
#define RIGHT_MOTOR_BCD_YELLOW_A 51
#define LEFT_MOTOR_BCD_WHITE_B 53
#define LEFT_MOTOR_BCD_YELLOW_A 52

#define FRONT_LEFT_DISTANCE 0
#define FRONT_RIGHT_DISTANCE 1
#define BACK_LEFT_DISTANCE 2
#define BACK_RIGHT_DISTANCE 3

#endif
